[package]
name = "example"
version = "0.1.0"
authors = ["Luma <world@luma.email>"]
build = "build.rs"
edition = "2021"

[build-dependencies]
rustsourcebundler = { path = ".." }

[dependencies]
rustsourcebundler = { path = ".." }
